CREATE DATABASE IF NOT EXISTS day16;
USE day16;
CREATE TABLE IF NOT EXISTS user(
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(20),
  password VARCHAR(20)
);

INSERT INTO user VALUES(NULL,'tom','123');
INSERT INTO user VALUES(NULL, '张三', '123');